[versions]
app = "5.0.0"
aboutlibraries = "10.9.2"
accompanist = "0.32.0"
activity = "1.8.1"
android = "8.1.4"
android-core = "1.12.0"
appcompat = "1.6.1"
appdirs = "1.2.2"
blurhash = "0.1.0"
cast = "21.3.0"
compose = "1.5.11"
complete-kotlin = "1.1.0"
context-menu = "0.2.0"
coroutines = "1.7.3"
datastore = "1.0.0"
datetime = "0.4.1"
decompose = "2.1.4-compose-experimental"
firebase = "1.10.4"
flowredux = "1.2.0"
grpc = "1.59.0"
instesx = "0.1.0-alpha10"
jsunpacker = "1.0.2"
kamel = "0.9.0"
kcef = "2023.10.13"
kodein = "7.21.0"
kotlin = "1.9.21"
ksp = "1.9.21-1.0.15"
ktor = "2.3.6"
ktorfit = "1.10.1"
ktsoup = "0.3.0"
lang = "3.14.0"
material = "1.10.0"
media3 = "1.2.0"
moko-resources = "0.23.0"
multidex = "2.0.1"
napier = "2.6.1"
osdetector = "1.7.3"
parcelable = "1.2.0"
protobuf = "0.9.4"
protoc = "3.24.4"
realm = "1.12.0"
sekret = "0.2.1"
serialization-json = "1.6.0"
splashscreen = "1.0.1"
sqldelight = "2.0.0"
turbine = "1.0.0"
versions = "0.50.0"
vlcj = "4.8.2"
windowsize-multiplatform = "0.3.1"
window-styler = "0.3.2"

[libraries]
aboutlibraries =  { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibraries-compose =  { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "aboutlibraries" }
accompanist-uicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
android = { group = "androidx.core", name = "core-ktx", version.ref = "android-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
appdirs = { group = "net.harawata", name = "appdirs", version.ref = "appdirs" }
blurhash = { group = "com.vanniktech", name = "blurhash", version.ref = "blurhash" }
cast = { group = "com.google.android.gms", name = "play-services-cast", version.ref = "cast" }
cast-framework = { group = "com.google.android.gms", name = "play-services-cast-framework", version.ref = "cast" }
compose-ui-util = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "compose" }
context-menu = { group = "io.github.dzirbel", name = "compose-material-context-menu", version.ref = "context-menu" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-js = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-js", version.ref = "coroutines" }
datastore = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
datastore-android = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose-jetbrains", version.ref = "decompose" }
firebase-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "firebase" }
firebase-store = { group = "dev.gitlive", name = "firebase-firestore", version.ref = "firebase" }
flowredux = { group = "com.freeletics.flowredux", name = "flowredux", version.ref = "flowredux" }
grpc = { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpc" }
insetsx = { group = "com.moriatsushi.insetsx", name = "insetsx", version.ref = "instesx" }
jsunpacker = { group = "dev.datlag.jsunpacker", name = "jsunpacker", version.ref = "jsunpacker" }
kamel = { group = "media.kamel", name = "kamel-image", version.ref = "kamel" }
kodein = { group = "org.kodein.di", name = "kodein-di", version.ref = "kodein" }
kodein-compose = { group = "org.kodein.di", name = "kodein-di-framework-compose", version.ref = "kodein" }
ktor = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-jvm = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-apple = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorfit = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib", version.ref = "ktorfit" }
ktorfit-ksp = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-ksp", version.ref = "ktorfit" }
ktsoup = { group = "org.drewcarlson", name = "ktsoup-core", version.ref = "ktsoup" }
ktsoup-fs = { group = "org.drewcarlson", name = "ktsoup-fs", version.ref = "ktsoup" }
ktsoup-ktor = { group = "org.drewcarlson", name = "ktsoup-ktor", version.ref = "ktsoup" }
lang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
media3 = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
media3-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
media3-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-smooth = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-cast = { group = "androidx.media3", name = "media3-cast", version.ref = "media3" }
moko-resources-compose = { group = "dev.icerock.moko", name = "resources-compose", version.ref = "moko-resources" }
moko-resources-generator = { group = "dev.icerock.moko", name = "resources-generator", version.ref = "moko-resources" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }
parcelable = { group = "com.arkivanov.essenty", name = "parcelable", version.ref = "parcelable" }
permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
protobuf = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protoc" }
protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protoc" }
realm = { group = "io.realm.kotlin", name = "library-base", version.ref = "realm" }
realm-sync = { group = "io.realm.kotlin", name = "library-sync", version.ref = "realm" }
sekret = { group = "dev.datlag.sekret", name = "sekret", version.ref = "sekret" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-native = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
vlcj = { group = "uk.co.caprica", name = "vlcj", version.ref = "vlcj" }
webview-android = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist" }
webview-desktop = { group = "dev.datlag", name = "kcef", version.ref = "kcef" }
windowsize-multiplatform = { group = "dev.chrisbanes.material3", name = "material3-window-size-class-multiplatform", version.ref = "windowsize-multiplatform" }
window-styler = { group = "com.mayakapps.compose", name = "window-styler", version.ref = "window-styler" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
complete-kotlin = { id = "com.louiscad.complete-kotlin", version.ref = "complete-kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }
parcelize = { id = "kotlin-parcelize", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }
sekret = { id = "dev.datlag.sekret", version.ref = "sekret" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }