name: Build Mac Package

on:
  workflow_dispatch:

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create Sekrets
        run: |
          ./gradlew createSekretProperties -Pkey=GITHUB_CLIENT_ID -Pvalue=${{ secrets.GH_CLIENT_ID }};
          ./gradlew createSekretProperties -Pkey=GITHUB_CLIENT_SECRET -Pvalue=${{ secrets.GH_CLIENT_SECRET }};
          ./gradlew createSekretProperties -Pkey=FIREBASE_PROJECT -Pvalue=${{ secrets.FIREBASE_PROJECT }};
          ./gradlew createSekretProperties -Pkey=FIREBASE_APPLICATION -Pvalue=${{ secrets.FIREBASE_APPLICATION }};
          ./gradlew createSekretProperties -Pkey=FIREBASE_API_KEY -Pvalue=${{ secrets.FIREBASE_API_KEY }}

      - name: Generate Sekret binary
        run: ./gradlew composeApp:createSekretNativeBinary

      - name: Copy Sekrets
        run: ./gradlew composeApp:copySekretNativeBinary

      - name: Moko
        run: ./gradlew composeApp:generateMR; ./gradlew generateMR

      - name: Package
        run: ./gradlew composeApp:packageDmg; ./gradlew composeApp:packageUberJarForCurrentOS

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/release/main/dmg/*.dmg
            composeApp/build/compose/jars/Burning-Series-*.jar
          retention-days: 1