name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Export libraries on Ubuntu and Mac
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: ./gradlew app:exportLibraryDefinitions -PaboutLibraries.exportPath=src/commonMain/assets/

      - name: Export libraries on Windows
        if: matrix.os == 'windows-latest'
        run: gradlew.bat app:exportLibraryDefinitions -PaboutLibraries.exportPath=src/commonMain/assets/ || gradlew.bat app:exportLibraryDefinitions -PaboutLibraries.exportPath=app/src/commonMain/assets/

      - name: Create package on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew packageDeb

      - name: Create package on Windows
        if: matrix.os == 'windows-latest'
        run: gradlew.bat packageExe; gradlew.bat packageMsi
        working-directory: ${{ github.workspace }}

      - name: Create package on Mac
        if: matrix.os == 'macos-latest'
        run: ./gradlew packageDmg

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/release/main/deb/*.deb
            ./build/release/main/exe/*.exe
            ./build/release/main/msi/*.msi
            ./build/release/main/dmg/*.dmg

  app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Build
        run: ./gradlew assembleRelease && ./gradlew bundleRelease

      - name: Move APK file(s)
        run: mv ./app/build/outputs/apk/release/*.apk ./app/release/

      - name: Move AAB file(s)
        run: mv ./app/build/outputs/bundle/release/*.aab ./app/release/

      - name: Remove "-unsigned" from filename(s)
        run: for filename in ./app/release/*-unsigned*; do mv "./$filename" "./$(echo "$filename" | sed -e 's/-unsigned//g')";  done

      - name: List all release files
        run: ls ./app/release/

      - uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: app/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 30.0.2

      - name: List signed files
        run: echo "Signed ${{ steps.sign_app.outputs.signedFilesCount }} files called ${{ steps.sign_app.outputs.signedFiles }}"

      - name: Split signed files
        uses: xom9ikk/split@v1
        id: split
        with:
          string: ${{ steps.sign_app.outputs.signedFiles }}
          separator: ':'
          limit: 2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.split.outputs._0 }}
            ${{ steps.split.outputs._1 }}