name: Build Windows Package

on:
  workflow_dispatch:


jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create Sekrets
        run: |
          gradle createSekretProperties -Pkey=MONGO_APPLICATION -Pvalue=${{ secrets.MONGO_APPLICATION }};
          gradle createSekretProperties -Pkey=WRAP_API -Pvalue=${{ secrets.WRAP_API }};
          gradle createSekretProperties -Pkey=FIREBASE_PROJECT -Pvalue=${{ secrets.FIREBASE_PROJECT }};
          gradle createSekretProperties -Pkey=FIREBASE_APPLICATION -Pvalue=${{ secrets.FIREBASE_APPLICATION }};
          gradle createSekretProperties -Pkey=FIREBASE_API_KEY -Pvalue=${{ secrets.FIREBASE_API_KEY }}
        working-directory: ${{ github.workspace }}

      - name: Generate Sekrets
        run: gradle generateSekret
        working-directory: ${{ github.workspace }}

      - name: Create native lib
        run: gradle app:shared:createNativeLib
        working-directory: ${{ github.workspace }}

      - name: Package
        run: gradle app:desktop:packageExe; gradle app:desktop:packageMsi
        working-directory: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/release/main/exe/*.exe
            build/release/main/msi/*.msi
          retention-days: 1