name: Build Windows Package

on:
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create Sekrets
        run: |
          gradle createSekretProperties -Pkey=GITHUB_CLIENT_ID -Pvalue=${{ secrets.GH_CLIENT_ID }};
          gradle createSekretProperties -Pkey=GITHUB_CLIENT_SECRET -Pvalue=${{ secrets.GH_CLIENT_SECRET }};
          gradle createSekretProperties -Pkey=FIREBASE_PROJECT -Pvalue=${{ secrets.FIREBASE_PROJECT }};
          gradle createSekretProperties -Pkey=FIREBASE_APPLICATION -Pvalue=${{ secrets.FIREBASE_APPLICATION }};
          gradle createSekretProperties -Pkey=FIREBASE_API_KEY -Pvalue=${{ secrets.FIREBASE_API_KEY }}
        working-directory: ${{ github.workspace }}

      - name: Generate Sekret binary
        run: gradle composeApp:createSekretNativeBinary
        working-directory: ${{ github.workspace }}

      - name: Copy Sekrets
        run: gradle composeApp:copySekretNativeBinary
        working-directory: ${{ github.workspace }}

      - name: Package
        run: gradle composeApp:packageExe; gradle composeApp:packageMsi; gradle composeApp:packageUberJarForCurrentOS
        working-directory: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/release/main/exe/*.exe
            build/release/main/msi/*.msi
            composeApp/build/compose/jars/Burning-Series-*.jar
          retention-days: 1